
FROM node:latest as node
LABEL org.opencontainers.image.source='https://github.com/vishuhanda/nginx-app'
RUN apt-get update && apt-get add --no-cache chromium
WORKDIR /app
ENV CHROME_BIN=/usr/bin/chromium-browser
COPY . .
RUN npm install
RUN npm test
RUN npm run build --prod


FROM nginx:alpine
COPY --from=node /app/dist/nginx-app /usr/share/nginx/html
EXPOSE 80
