
FROM node:latest as node
LABEL org.opencontainers.image.source="https://github.com/vishuhanda/nginx-app"
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --prod

FROM nginx:alpine
COPY --from=node /app/dist/nginx-app /usr/share/nginx/html
EXPOSE 80
