name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login -u ${{ github.actor}} -p ${{ github.token }} ghcr.io
        docker build . --file dockerFile --tag ghcr.io/${{github.actor}}/nginx-app:$(date +%s)
        docker push ghcr.io/${{github.actor}}/nginx-app:$(date +%s)
