name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login -u ${{ github.actor}} -p ${{ github.token }} ghcr.io
        docker build . --file dockerFile --tag ghcr.io/${{github.actor}}/nginx-app:${{secrets.MAJOR_VERSION}}.${{secrets.MINOR_VERSION}}
        docker push ghcr.io/${{github.actor}}/nginx-app:${{secrets.MAJOR_VERSION}}.${{secrets.MINOR_VERSION}}

    -  uses: hmanzur/actions-set-secret@v2.0.0
       with:
          name: 'MINOR_VERSION'
          value: $((${{ secrets.MINOR_VERSION }} + 1))
          repository: ${{github.actor}}/github.repository
          token: ${{ github.token }}    

    -  uses: hmanzur/actions-set-secret@v2.0.0
       with:
          name: 'MAJOR_VERSION'
          value: $((${{ secrets.MAJOR_VERSION }} + 1))
          repository: ${{github.actor}}/${{github.repository}}
          token: ${{ github.token }}    