name: Docker Image CI
on:
  push:
    branches: [ "main" ]
env:
  GHCR_IO : ${{ secrets.GHCR_IO }}
jobs:

  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ github.token }}
          version-file: './version.yaml'

      - name: create release
        if: steps.changelog.outputs.skipped == 'false'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ github.token }}
          tag	: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

          

#      - name: Build the Docker image
#        run: |
#          echo "token ${{ env.GHCR_IO }}"
#          echo "version ${{steps.changelog.outputs.tag}}"
#          echo "changelog ${{steps.changelog.outputs.changelog}}"
#          docker login -u ${{ github.actor}} -p ${{ env.GHCR_IO }} ghcr.io
#          docker build . --file dockerFile --tag ghcr.io/${{github.actor}}/nginx-app:${{ steps.changelog.outputs.tag }}
#          docker push ghcr.io/${{github.actor}}/nginx-app:${{ steps.changelog.outputs.tag }}
