name: Docker Image CI
on:
  push:
    branches: [ "main" ]
env:
  GHCR_IO : ${{ secrets.GHCR_IO }}
jobs:

  build_docker_image:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: semantic-versioning-tag
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ env.GHCR_IO }}

      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ env.GHCR_IO }}
        with:
           tag_name: ${{ steps.build_docker_image.outputs.tag }}
           release_name: ${{ steps.build_docker_image.outputs.tag }}
           body: ${{ steps.build_docker_image.outputs.clean_change_log }}

      - name: Build the Docker image
        run: |
          echo "token ${{ env.GHCR_IO }}"
          echo "version ${{steps.build_docker_image.outputs.tag}}"
          echo "changelog ${{steps.build_docker_image.outputs.changelog}}"
          docker login -u ${{ github.actor}} -p ${{ env.GHCR_IO }} ghcr.io
          docker build . --file dockerFile --tag ghcr.io/${{github.actor}}/nginx-app:${{ steps.build_docker_image.outputs.tag }}
          docker push ghcr.io/${{github.actor}}/nginx-app:${{ steps.build_docker_image.outputs.tag }}
