name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  GHCR_IO : ${{ secrets.GHCR_IO }}
jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: semantic-versioning-tag
        uses: LongOddCode/semantic-versioning-tag@0.6.0
        id: svt

      - name: validation and set params
        run: |
                 echo ${{ steps.svt.outputs.major }}
                 echo ${{ steps.svt.outputs.minor }}
                 echo ${{ steps.svt.outputs.patch }}
                 echo ${{ steps.svt.outputs.prerelease }}
                 echo ${{ steps.svt.outputs.buildmetadata }}


    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: |
    #     echo "token ${{ env.GHCR_IO }}"
    #     echo "secrets ${{ secrets.MAJOR_VERSION }} ${{ secrets.MINOR_VERSION }} "
    #     docker login -u ${{ github.actor}} -p ${{ env.GHCR_IO }} ghcr.io
    #     docker build . --file dockerFile --tag ghcr.io/${{github.actor}}/nginx-app:${{steps.changelog.outputs.tag}}
    #     docker push ghcr.io/${{github.actor}}/nginx-app:${{steps.changelog.outputs.tag}}

    #     # docker build . --file dockerFile --tag ghcr.io/${{github.actor}}/nginx-app:${{secrets.MAJOR_VERSION}}.${{secrets.MINOR_VERSION}}
    #     # docker push ghcr.io/${{github.actor}}/nginx-app:${{secrets.MAJOR_VERSION}}.${{secrets.MINOR_VERSION}}
    # -  uses: hmanzur/actions-set-secret@v2.0.0
    #    with:
    #       name: 'MINOR_VERSION'
    #       value: ${{ secrets.MINOR_VERSION }} + 1
    #       repository: ${{github.repository}}
    #       token: ${{ env.GHCR_IO }}

    # -  uses: hmanzur/actions-set-secret@v2.0.0
    #    with:
    #       name: 'MAJOR_VERSION'
    #       value: ${{ secrets.MAJOR_VERSION }} + 1
    #       repository: ${{github.repository}}
    #       token: ${{ env.GHCR_IO }}
