name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  GHCR_IO : ${{ secrets.GHCR_IO }}
jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: semantic-versioning-tag
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ env.GHCR_IO }}

      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ env.GHCR_IO }}
        with:
           tag_name: ${{ steps.changelog.outputs.tag }}
           release_name: ${{ steps.changelog.outputs.tag }}
           body: ${{ steps.changelog.outputs.clean_change_log }}

     - name: Build the Docker image
       run: |
          echo "token ${{ env.GHCR_IO }}"
          echo "secrets ${{ secrets.MAJOR_VERSION }} ${{ secrets.MINOR_VERSION }} "
          docker login -u ${{ github.actor}} -p ${{ env.GHCR_IO }} ghcr.io
          docker build . --file dockerFile --tag ghcr.io/${{github.actor}}/nginx-app:${{ steps.svt.outputs.major }}.${{ steps.svt.outputs.minor }}.${{ steps.svt.outputs.patch }}
          docker push ghcr.io/${{github.actor}}/nginx-app:${{ steps.svt.outputs.major }}.${{ steps.svt.outputs.minor }}.${{ steps.svt.outputs.patch }}
